    np.array([1,2,3])                               	 One dimensional array
    np.array([(1,2,3),(4,5,6)])                     	 Two dimensional array
    np.array([[[1,2,3],[6,7,8]],[[1,2,3],[6,7,8]]]) 	 Three dimensional array
    np.zeros(3)                                     	 1D array of length 3 all values 0
    np.ones((3,4))                                  	 3x4 array with all values 1
    np.eye(5)                                       	 5x5 array of 0 with 1 on diagonal (Identity matrix)
    np.linspace(0,100,6)                            	 Array of 6 evenly divided values from 0 to 100
    np.arange(0,10,3)                               	 Array of values from 0 to less than 10 with step 3 (eg [0,3,6,9])
    np.full((2,3),8)                                	 2x3 array with all values 8
    np.random.rand(4,5)                             	 4x5 array of random floats between 0–1
    np.random.rand(6,7)*100                         	 6x7 array of random floats between 0–100
    np.random.randint(5,size=(2,3))                 	 2x3 array with random ints between 0–4

### One dimensional array

In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

### Two dimensional array

In [3]:
import numpy as np
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Three Dimensional Array

In [4]:
import numpy as np
arr3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
arr3

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

### np.zeros

In [5]:
import numpy as np
arr4 = np.zeros(3)
arr4

array([0., 0., 0.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
np.zeros((2,3,2,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [19]:
np.zeros((2,2,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [20]:
np.zeros((2,2,4),dtype=bool)

array([[[False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False]]])

### np.ones

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [23]:
np.ones((2,3,2,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [24]:
np.ones((2,3,2,4),dtype=int)

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1]]]])

### np.eye

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.eye((4),dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

### np.linspace

In [138]:
np.linspace(2,4)

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [141]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [40]:
np.linspace(2,4,axis=0)

array([2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531,
       2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694,
       2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857,
       2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ,
       2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184,
       3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347,
       3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ,
       3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673,
       3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837,
       3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ])

In [41]:
np.linspace(2,4,10,axis=1)

AxisError: destination: axis 1 is out of bounds for array of dimension 1

In [46]:
np.linspace(2,4,10,dtype=int)

array([2, 2, 2, 2, 2, 3, 3, 3, 3, 4])

In [64]:
np.linspace(2,4,10,dtype='<U4')

array(['2.0', '2.22', '2.44', '2.66', '2.88', '3.11', '3.33', '3.55',
       '3.77', '4.0'], dtype='<U4')

### np.arange

In [69]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [71]:
np.arange(10,40,5)

array([10, 15, 20, 25, 30, 35])

In [74]:
np.arange(10,40,3.5)

array([10. , 13.5, 17. , 20.5, 24. , 27.5, 31. , 34.5, 38. ])

In [75]:
np.arange(10,40,3.5,dtype=int)

array([10, 13, 16, 19, 22, 25, 28, 31, 34])

### np.full

In [76]:
np.full(2,4)

array([4, 4])

In [83]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [88]:
np.full((3,4),10,dtype=float)

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

### np.random.rand

In [89]:
np.random.rand(10)

array([0.93595092, 0.27931582, 0.54176939, 0.19013404, 0.63332248,
       0.42827274, 0.61473156, 0.17672885, 0.26292431, 0.86832983])

In [90]:
np.random.rand(2,4)

array([[0.11599044, 0.20463269, 0.51216988, 0.01218398],
       [0.9782129 , 0.6990004 , 0.87495921, 0.05987112]])

In [92]:
np.random.rand(2,2,4)

array([[[0.76465046, 0.26474001, 0.00675373, 0.78237321],
        [0.10432083, 0.84009746, 0.30695105, 0.3818165 ]],

       [[0.9243163 , 0.68014638, 0.87648561, 0.87816706],
        [0.20594086, 0.76885753, 0.67088909, 0.1310523 ]]])

In [94]:
np.random.rand(2,2,2,4)

array([[[[0.04257741, 0.45335223, 0.85191917, 0.25797442],
         [0.80204968, 0.72518089, 0.07653077, 0.5459374 ]],

        [[0.941936  , 0.26918895, 0.1792248 , 0.35121011],
         [0.19403493, 0.26132928, 0.95134387, 0.39369675]]],


       [[[0.15685187, 0.34510014, 0.0261992 , 0.54696285],
         [0.07257355, 0.68905906, 0.22609464, 0.67790817]],

        [[0.96215359, 0.5992577 , 0.65196441, 0.64528312],
         [0.24748953, 0.80510867, 0.45140984, 0.12227276]]]])

In [99]:
np.random.rand(6,4)*100

array([[17.71875198,  5.5376167 , 63.7370818 , 69.82750874],
       [ 2.41893902,  4.08583364, 35.6505479 , 63.16850272],
       [60.18745614, 50.22575411, 28.81590254, 48.94090765],
       [67.89605214, 34.52743424, 58.15766977, 16.58485115],
       [43.96852775, 32.19334684, 54.26877564,  3.42138001],
       [52.42198683, 62.6318134 , 46.52337387, 25.55657469]])

In [112]:
np.random.seed(24)
np.random.rand(6,4)*100

array([[96.00173033, 69.95120499, 99.98672926, 22.00672998],
       [36.1056354 , 73.98409902, 99.64557251, 31.63469778],
       [13.65445798, 38.39800102, 32.05192836, 36.64147531],
       [70.96515626, 90.01424305, 53.41154392, 24.72937649],
       [67.18065626, 56.17291073, 54.25598767, 89.34476037],
       [84.27795496, 30.60125899, 63.11697775, 68.02388604]])

### np.random.randint

In [116]:
np.random.randint(10)

3

In [125]:
np.random.randint((4,10))

array([2, 5])

In [128]:
np.random.randint((4,10,100))

array([ 2,  5, 39])

In [130]:
np.random.randint(5,size=(2,3)) 

array([[2, 2, 1],
       [3, 0, 3]])

In [136]:
np.random.randint((4,10,100),size=(2,3))

array([[ 2,  0, 13],
       [ 2,  9, 40]])