In [8]:
import numpy as np
arr = np.random.rand(2,2,2,4)
arr

array([[[[0.24968968, 0.67888908, 0.59723256, 0.52635849],
         [0.49189583, 0.94259834, 0.84167634, 0.4646275 ]],

        [[0.02255237, 0.6304196 , 0.9485281 , 0.42176567],
         [0.66079651, 0.41628761, 0.48503585, 0.11381837]]],


       [[[0.34824024, 0.70450238, 0.04382303, 0.13397263],
         [0.11046542, 0.22133842, 0.55158038, 0.93984776]],

        [[0.63534427, 0.0989151 , 0.04982724, 0.35246413],
         [0.87051115, 0.55848019, 0.41284565, 0.45020875]]]])

In [9]:
arr.size

32

In [10]:
arr.shape

(2, 2, 2, 4)

In [11]:
arr.ndim

4

In [16]:
np.info(arr)

class:  ndarray
shape:  (2, 2, 2, 4)
strides:  (128, 64, 32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x31d4848
byteorder:  little
byteswap:  False
type: float64


In [17]:
arr.dtype

dtype('float64')

In [26]:
arr = np.random.randint(2)
arr

1

In [33]:
arr = np.random.randint((4,10,100),size=(2,3))
arr

array([[ 2,  8, 78],
       [ 0,  9, 57]])

In [34]:
arr.dtype

dtype('int32')

In [36]:
arr = np.random.randint((4,10,100),size=(2,3))
arr

array([[ 3,  0, 41],
       [ 1,  2, 72]])

In [42]:
list1 = arr.tolist()

In [43]:
list1

[[3, 0, 41], [1, 2, 72]]

In [44]:
type(list1)

list