 ### Copying/sorting/reshaping

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,100,size=(4,4))

In [3]:
arr

array([[75, 89, 57, 78],
       [72,  6, 24, 73],
       [74, 54, 97, 76],
       [42, 31, 68, 50]])

In [4]:
arr1 = arr.copy()
arr1

array([[75, 89, 57, 78],
       [72,  6, 24, 73],
       [74, 54, 97, 76],
       [42, 31, 68, 50]])

In [5]:
arr2 = np.copy(arr1)
arr2

array([[75, 89, 57, 78],
       [72,  6, 24, 73],
       [74, 54, 97, 76],
       [42, 31, 68, 50]])

In [11]:
arr2.view(int)

array([[75, 89, 57, 78],
       [72,  6, 24, 73],
       [74, 54, 97, 76],
       [42, 31, 68, 50]])

In [16]:
arr3 = np.zeros((4,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
arr3.view(int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
arr2

array([[75, 89, 57, 78],
       [72,  6, 24, 73],
       [74, 54, 97, 76],
       [42, 31, 68, 50]])

In [22]:
np.sort(arr2)

array([[57, 75, 78, 89],
       [ 6, 24, 72, 73],
       [54, 74, 76, 97],
       [31, 42, 50, 68]])

In [23]:
np.sort(arr2,axis=0)

array([[42,  6, 24, 50],
       [72, 31, 57, 73],
       [74, 54, 68, 76],
       [75, 89, 97, 78]])

In [24]:
np.sort(arr2,axis=1)

array([[57, 75, 78, 89],
       [ 6, 24, 72, 73],
       [54, 74, 76, 97],
       [31, 42, 50, 68]])

In [25]:
arr2.flatten()

array([75, 89, 57, 78, 72,  6, 24, 73, 74, 54, 97, 76, 42, 31, 68, 50])

In [26]:
arr2.T

array([[75, 72, 74, 42],
       [89,  6, 54, 31],
       [57, 24, 97, 68],
       [78, 73, 76, 50]])

In [35]:
arr4 = np.random.rand(2,2,2,4)
arr4

array([[[[0.51850154, 0.47560775, 0.46605059, 0.01616007],
         [0.28238903, 0.29310049, 0.77050905, 0.73029526]],

        [[0.46611168, 0.40836413, 0.86369289, 0.1403873 ],
         [0.56956087, 0.78573582, 0.168723  , 0.26073256]]],


       [[[0.62967472, 0.40348536, 0.58342962, 0.02720351],
         [0.51536019, 0.2592979 , 0.39105477, 0.98703558]],

        [[0.52285501, 0.01986818, 0.68857092, 0.99167381],
         [0.70402211, 0.76704277, 0.51481448, 0.15954059]]]])

In [37]:
arr4.reshape(8,4)

array([[0.51850154, 0.47560775, 0.46605059, 0.01616007],
       [0.28238903, 0.29310049, 0.77050905, 0.73029526],
       [0.46611168, 0.40836413, 0.86369289, 0.1403873 ],
       [0.56956087, 0.78573582, 0.168723  , 0.26073256],
       [0.62967472, 0.40348536, 0.58342962, 0.02720351],
       [0.51536019, 0.2592979 , 0.39105477, 0.98703558],
       [0.52285501, 0.01986818, 0.68857092, 0.99167381],
       [0.70402211, 0.76704277, 0.51481448, 0.15954059]])

In [46]:
arr5 = arr4.resize((8,4))
arr5

In [48]:
arr4.resize((4,4,2))