In [1]:
import numpy as np
arr = np.random.randint(2,20,10)
arr

array([16, 13, 19,  9, 19,  2, 16,  4, 13,  4])

In [2]:
np.append(arr,[10,11,12])

array([16, 13, 19,  9, 19,  2, 16,  4, 13,  4, 10, 11, 12])

In [3]:
np.insert(arr,2,[100,101,102])

array([ 16,  13, 100, 101, 102,  19,   9,  19,   2,  16,   4,  13,   4])

In [4]:
np.delete(arr,3)

array([16, 13, 19, 19,  2, 16,  4, 13,  4])

In [5]:
arr = np.random.rand(2,2,2,4)
arr

array([[[[0.90897207, 0.04152553, 0.07996033, 0.80540249],
         [0.78988163, 0.71688958, 0.45476833, 0.68290223]],

        [[0.30780092, 0.09524577, 0.90414492, 0.30217386],
         [0.65928895, 0.59794512, 0.22500252, 0.64330017]]],


       [[[0.67279481, 0.38740217, 0.87723176, 0.48528364],
         [0.3444971 , 0.3074181 , 0.22853158, 0.9799826 ]],

        [[0.50848123, 0.43971073, 0.43442678, 0.53329552],
         [0.47531756, 0.20221154, 0.49180019, 0.40053496]]]])

In [6]:
np.delete(arr,1,axis=1)

array([[[[0.90897207, 0.04152553, 0.07996033, 0.80540249],
         [0.78988163, 0.71688958, 0.45476833, 0.68290223]]],


       [[[0.67279481, 0.38740217, 0.87723176, 0.48528364],
         [0.3444971 , 0.3074181 , 0.22853158, 0.9799826 ]]]])

## Combining/splitting

In [7]:
a = np.array([10,20,30,40,50])
b = np.array([100,200,300,400,500])
np.concatenate((a,b))

array([ 10,  20,  30,  40,  50, 100, 200, 300, 400, 500])

In [8]:
np.concatenate((a,b),axis=0)

array([ 10,  20,  30,  40,  50, 100, 200, 300, 400, 500])

In [9]:
a = np.array([[10,20,30,40,50],[60,70,80,90,100]])
b = np.array([[100,200,300,400,500],[600,700,800,900,1000]])
np.concatenate((a,b))
np.concatenate((a,b),axis=1)

array([[  10,   20,   30,   40,   50,  100,  200,  300,  400,  500],
       [  60,   70,   80,   90,  100,  600,  700,  800,  900, 1000]])

In [10]:
np.split(a,2)

[array([[10, 20, 30, 40, 50]]), array([[ 60,  70,  80,  90, 100]])]

In [11]:
np.hsplit(a,5)

[array([[10],
        [60]]), array([[20],
        [70]]), array([[30],
        [80]]), array([[40],
        [90]]), array([[ 50],
        [100]])]

## Indexing/slicing/subsetting

In [12]:
a = np.random.rand(2,5,2,4)
a

array([[[[1.98590066e-01, 3.54256069e-01, 9.06408010e-01,
          6.30686143e-01],
         [2.94390725e-01, 5.90181597e-02, 1.41875404e-02,
          7.10648164e-01]],

        [[1.03336172e-02, 8.67412643e-01, 7.29787140e-01,
          4.82936055e-01],
         [1.08961763e-01, 1.82599246e-01, 4.61540651e-01,
          1.73803071e-01]],

        [[8.13098603e-01, 2.15338919e-01, 2.93034778e-01,
          1.76955593e-01],
         [4.46030150e-01, 7.14533105e-01, 6.57671570e-01,
          8.96398024e-01]],

        [[3.13163709e-01, 1.02480647e-01, 3.26700837e-01,
          5.68457381e-01],
         [4.90067580e-01, 6.78873873e-01, 1.57024215e-01,
          3.38840857e-01]],

        [[8.92114393e-01, 8.57850116e-01, 7.92394464e-01,
          8.98774199e-01],
         [6.78795411e-01, 6.93406580e-01, 3.77732764e-01,
          9.84019039e-02]]],


       [[[4.61112915e-01, 1.62912563e-01, 1.80904084e-01,
          3.86819188e-01],
         [1.49865811e-01, 3.22155658e-01, 6.79551433e

In [13]:
a[1]

array([[[4.61112915e-01, 1.62912563e-01, 1.80904084e-01, 3.86819188e-01],
        [1.49865811e-01, 3.22155658e-01, 6.79551433e-01, 9.21965273e-01]],

       [[2.77997577e-01, 6.40973731e-01, 3.62103168e-01, 7.20830544e-01],
        [6.64474581e-01, 6.03971890e-01, 6.02318360e-01, 4.04916767e-01]],

       [[2.32186324e-01, 9.53613935e-03, 2.99668483e-01, 1.89239025e-01],
        [9.23199542e-02, 9.58982542e-01, 3.35040869e-01, 8.46139247e-01]],

       [[3.56215452e-01, 2.40671718e-01, 3.94317319e-01, 4.11832726e-01],
        [6.92269561e-01, 5.08080597e-01, 5.77697261e-01, 1.67383738e-01]],

       [[6.38413783e-04, 1.78384091e-01, 5.69271917e-01, 2.06376855e-01],
        [9.95677187e-01, 7.70254625e-01, 3.88289429e-01, 8.44454095e-01]]])

In [14]:
a[1,2]

array([[0.23218632, 0.00953614, 0.29966848, 0.18923902],
       [0.09231995, 0.95898254, 0.33504087, 0.84613925]])

In [17]:
a[1,2]=10

In [18]:
a[1,2,0,1]=20

In [19]:
a[1,2]

array([[10., 20., 10., 10.],
       [10., 10., 10., 10.]])

In [21]:
a[0:1]

array([[[[0.19859007, 0.35425607, 0.90640801, 0.63068614],
         [0.29439073, 0.05901816, 0.01418754, 0.71064816]],

        [[0.01033362, 0.86741264, 0.72978714, 0.48293605],
         [0.10896176, 0.18259925, 0.46154065, 0.17380307]],

        [[0.8130986 , 0.21533892, 0.29303478, 0.17695559],
         [0.44603015, 0.71453311, 0.65767157, 0.89639802]],

        [[0.31316371, 0.10248065, 0.32670084, 0.56845738],
         [0.49006758, 0.67887387, 0.15702421, 0.33884086]],

        [[0.89211439, 0.85785012, 0.79239446, 0.8987742 ],
         [0.67879541, 0.69340658, 0.37773276, 0.0984019 ]]]])

In [22]:
a[0:1,0:1]

array([[[[0.19859007, 0.35425607, 0.90640801, 0.63068614],
         [0.29439073, 0.05901816, 0.01418754, 0.71064816]]]])

In [23]:
a[0:1,0:-1]

array([[[[0.19859007, 0.35425607, 0.90640801, 0.63068614],
         [0.29439073, 0.05901816, 0.01418754, 0.71064816]],

        [[0.01033362, 0.86741264, 0.72978714, 0.48293605],
         [0.10896176, 0.18259925, 0.46154065, 0.17380307]],

        [[0.8130986 , 0.21533892, 0.29303478, 0.17695559],
         [0.44603015, 0.71453311, 0.65767157, 0.89639802]],

        [[0.31316371, 0.10248065, 0.32670084, 0.56845738],
         [0.49006758, 0.67887387, 0.15702421, 0.33884086]]]])