In [8]:
import numpy as np
a = np.random.rand(2,2,4)
b = np.random.rand(2,2,4)

In [9]:
a,b

(array([[[0.00415026, 0.70894515, 0.58253532, 0.41302591],
         [0.19315623, 0.04443093, 0.18040115, 0.81679997]],
 
        [[0.07828287, 0.82652547, 0.62745598, 0.16831655],
         [0.57459419, 0.11140723, 0.15535227, 0.57228162]]]),
 array([[[6.70550423e-02, 7.15887977e-02, 3.37096477e-01, 4.62377941e-01],
         [7.39247577e-04, 7.42538091e-01, 8.70019991e-02, 2.83779101e-01]],
 
        [[8.91753204e-01, 4.84633940e-01, 4.16942669e-01, 3.80776798e-01],
         [3.25853492e-01, 8.50897267e-01, 2.49008079e-01, 2.63674376e-01]]]))

In [10]:
a+b

array([[[0.0712053 , 0.78053395, 0.9196318 , 0.87540385],
        [0.19389547, 0.78696902, 0.26740315, 1.10057907]],

       [[0.97003607, 1.31115941, 1.04439864, 0.54909335],
        [0.90044769, 0.9623045 , 0.40436035, 0.83595599]]])

In [11]:
np.add(a,b)

array([[[0.0712053 , 0.78053395, 0.9196318 , 0.87540385],
        [0.19389547, 0.78696902, 0.26740315, 1.10057907]],

       [[0.97003607, 1.31115941, 1.04439864, 0.54909335],
        [0.90044769, 0.9623045 , 0.40436035, 0.83595599]]])

In [12]:
a-b

array([[[-0.06290479,  0.63735635,  0.24543885, -0.04935203],
        [ 0.19241698, -0.69810716,  0.09339915,  0.53302086]],

       [[-0.81347034,  0.34189153,  0.21051331, -0.21246025],
        [ 0.2487407 , -0.73949004, -0.09365581,  0.30860724]]])

In [13]:
np.subtract(a,b)

array([[[-0.06290479,  0.63735635,  0.24543885, -0.04935203],
        [ 0.19241698, -0.69810716,  0.09339915,  0.53302086]],

       [[-0.81347034,  0.34189153,  0.21051331, -0.21246025],
        [ 0.2487407 , -0.73949004, -0.09365581,  0.30860724]]])

In [14]:
a/b

array([[[6.18932718e-02, 9.90301796e+00, 1.72809674e+00, 8.93264739e-01],
        [2.61287600e+02, 5.98365627e-02, 2.07352883e+00, 2.87829500e+00]],

       [[8.77853486e-02, 1.70546344e+00, 1.50489749e+00, 4.42034677e-01],
        [1.76335135e+00, 1.30929122e-01, 6.23884455e-01, 2.17041043e+00]]])

In [15]:
np.divide(a,b)

array([[[6.18932718e-02, 9.90301796e+00, 1.72809674e+00, 8.93264739e-01],
        [2.61287600e+02, 5.98365627e-02, 2.07352883e+00, 2.87829500e+00]],

       [[8.77853486e-02, 1.70546344e+00, 1.50489749e+00, 4.42034677e-01],
        [1.76335135e+00, 1.30929122e-01, 6.23884455e-01, 2.17041043e+00]]])

In [16]:
a*b

array([[[2.78295588e-04, 5.07525308e-02, 1.96370605e-01, 1.90974070e-01],
        [1.42790272e-04, 3.29916558e-02, 1.56952609e-02, 2.31790760e-01]],

       [[6.98089965e-02, 4.00562293e-01, 2.61613169e-01, 6.40910364e-02],
        [1.87233525e-01, 9.47961093e-02, 3.86839701e-02, 1.50895998e-01]]])

In [17]:
np.multiply(a,b)

array([[[2.78295588e-04, 5.07525308e-02, 1.96370605e-01, 1.90974070e-01],
        [1.42790272e-04, 3.29916558e-02, 1.56952609e-02, 2.31790760e-01]],

       [[6.98089965e-02, 4.00562293e-01, 2.61613169e-01, 6.40910364e-02],
        [1.87233525e-01, 9.47961093e-02, 3.86839701e-02, 1.50895998e-01]]])

In [18]:
a%b

array([[[4.15025595e-03, 6.46459699e-02, 2.45438846e-01, 4.13025910e-01],
        [2.12607962e-04, 4.44309271e-02, 6.39715481e-03, 2.49241764e-01]],

       [[7.82828659e-02, 3.41891527e-01, 2.10513306e-01, 1.68316549e-01],
        [2.48740702e-01, 1.11407232e-01, 1.55352269e-01, 4.49328641e-02]]])

In [19]:
np.mod(a,b)

array([[[4.15025595e-03, 6.46459699e-02, 2.45438846e-01, 4.13025910e-01],
        [2.12607962e-04, 4.44309271e-02, 6.39715481e-03, 2.49241764e-01]],

       [[7.82828659e-02, 3.41891527e-01, 2.10513306e-01, 1.68316549e-01],
        [2.48740702e-01, 1.11407232e-01, 1.55352269e-01, 4.49328641e-02]]])

In [21]:
np.power(a,b)

array([[[0.69227701, 0.97567581, 0.8334719 , 0.66441033],
        [0.99878523, 0.09905009, 0.86157152, 0.94419191]],

       [[0.1031392 , 0.91179995, 0.82338665, 0.50737264],
        [0.8348088 , 0.15453299, 0.62897234, 0.86315326]]])

In [22]:
np.array_equal(a,b)

False

In [24]:
a=np.array([1,2,3,4,5])
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [25]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [27]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [28]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [29]:
np.abs(a)

array([1, 2, 3, 4, 5])

In [32]:
np.ceil(a)

array([1., 2., 3., 4., 5.])

In [33]:
a = np.sin(a)
np.ceil(a)

array([ 1.,  1.,  1., -0., -0.])

In [34]:
np.floor(a)

array([ 0.,  0.,  0., -1., -1.])

In [35]:
np.round(a)

array([ 1.,  1.,  0., -1., -1.])

In [41]:
a = np.random.randint(1,10,10)
print(a)
np.mean(a)

[2 2 5 6 8 5 5 9 6 1]


4.9

In [42]:
np.sum(a)

49

In [43]:
np.min(a)

1

In [44]:
np.max(a)

9

In [45]:
a.min()

1

In [46]:
a.max()

9

In [47]:
a.sum()

49

In [48]:
a.max()

9

In [49]:
a=np.random.rand(2,2,4)

In [50]:
a

array([[[8.51717464e-01, 2.70838649e-02, 7.21330131e-01, 3.86293577e-01],
        [1.00388199e-01, 7.38139905e-04, 4.84079532e-01, 5.12193003e-01]],

       [[2.13949190e-01, 6.79812212e-01, 8.90484902e-01, 5.18844337e-02],
        [1.85528992e-01, 5.32169820e-01, 1.32193829e-01, 7.43794610e-01]]])

In [51]:
a.sum(axis=0)

array([[1.06566665, 0.70689608, 1.61181503, 0.43817801],
       [0.28591719, 0.53290796, 0.61627336, 1.25598761]])

In [52]:
a.sum(axis=1)

array([[0.95210566, 0.027822  , 1.20540966, 0.89848658],
       [0.39947818, 1.21198203, 1.02267873, 0.79567904]])